components:
- cli
- config
- docker
- docs
- global
- hooks
- installation
- kwalitee
- tests
- travis
- views
exclude_author_names:
- Jiri Kuncar <jiri.kuncar@gmail.com>
- Mateusz Susik <mateusz.susik@cern.ch>
- Yoan Blanc <yoan.blanc@cern.ch>
